const carBrands = [
	{ id: 1, name: "Acura" },
	{ id: 2, name: "Alfa Romeo" },
	{ id: 3, name: "Aston Martin" },
	{ id: 4, name: "Audi" },
	{ id: 5, name: "Bentley" },
	{ id: 6, name: "BMW" },
	{ id: 7, name: "Bugatti" },
	{ id: 8, name: "Buick" },
	{ id: 9, name: "Cadillac" },
	{ id: 10, name: "Chevrolet" },
	{ id: 11, name: "Chrysler" },
	{ id: 12, name: "Citroën" },
	{ id: 13, name: "Dodge" },
	{ id: 14, name: "Ferrari" },
	{ id: 15, name: "Fiat" },
	{ id: 16, name: "Ford" },
	{ id: 17, name: "GMC" },
	{ id: 18, name: "Honda" },
	{ id: 19, name: "Hyundai" },
	{ id: 20, name: "Infiniti" },
	{ id: 21, name: "Jaguar" },
	{ id: 22, name: "Jeep" },
	{ id: 23, name: "Kia" },
	{ id: 24, name: "Koenigsegg" },
	{ id: 25, name: "Lamborghini" },
	{ id: 26, name: "Land Rover" },
	{ id: 27, name: "Lexus" },
	{ id: 28, name: "Lincoln" },
	{ id: 29, name: "Maserati" },
	{ id: 30, name: "Mazda" },
	{ id: 31, name: "McLaren" },
	{ id: 32, name: "Mercedes-Benz" },
	{ id: 33, name: "Mini" },
	{ id: 34, name: "Mitsubishi" },
	{ id: 35, name: "Nissan" },
	{ id: 36, name: "Pagani" },
	{ id: 37, name: "Peugeot" },
	{ id: 38, name: "Porsche" },
	{ id: 39, name: "Ram" },
	{ id: 40, name: "Renault" },
	{ id: 41, name: "Rolls-Royce" },
	{ id: 42, name: "Seat" },
	{ id: 43, name: "Skoda" },
	{ id: 44, name: "Smart" },
	{ id: 45, name: "Subaru" },
	{ id: 46, name: "Suzuki" },
	{ id: 47, name: "Tesla" },
	{ id: 48, name: "Toyota" },
	{ id: 49, name: "Volkswagen" },
	{ id: 50, name: "Volvo" },
];

const carPricing = [
	{ id: 1, amount: "1000 $" },
	{ id: 2, amount: "5000 $" },
	{ id: 3, amount: "10000 $" },
	{ id: 4, amount: "50000 $" },
	{ id: 4, amount: "100000 $" },
];
const Category = [
	{ id: 1, name: "Sedan", icon: "/sedan.png" },
	{ id: 2, name: "Hatchback", icon: "/hatchback.png" },
	{ id: 3, name: "SUV", icon: "/suv.png" },
	{ id: 5, name: "Combi", icon: "/combi.png" },
	{ id: 6, name: "Coupé", icon: "/coupe.png" },
	{ id: 7, name: "Cabrio", icon: "/cabrio.png" },
	{ id: 8, name: "Minivan", icon: "/minivan.png" },
	{ id: 9, name: "Pick-up", icon: "/pickup.png" },
	{ id: 10, name: "Electric", icon: "/electric.png" },
];

export default {
	carBrands,
	carPricing,
	Category,
};
